import { NgayLe } from './interfaces';

export const NGAY_LE_DUONG_LICH: NgayLe[] = [
  { ngay:  1, thang:  1, noidung: 'Tết Dương lịch' },
  { ngay:  9, thang:  1, noidung: 'Ngày Học sinh - Sinh viên Việt Nam' },
  { ngay:  3, thang:  2, noidung: 'Ngày thành lập Đảng Cộng sản Việt Nam' },
  { ngay: 27, thang:  2, noidung: 'Ngày Thầy thuốc Việt Nam' },
  { ngay:  8, thang:  3, noidung: 'Ngày Quốc tế Phụ nữ' },
  { ngay: 26, thang:  3, noidung: 'Ngày thành lập Đoàn Thanh niên Cộng sản Hồ Chí Minh' },
  { ngay: 21, thang:  4, noidung: 'Ngày Sách Việt Nam' },
  { ngay: 30, thang:  4, noidung: 'Ngày Thống nhất đất nước' },
  { ngay:  1, thang:  5, noidung: 'Ngày Quốc tế Lao động' },
  { ngay: 15, thang:  5, noidung: 'Ngày thành lập Đội Thiếu niên Tiền phong Hồ Chí Minh' },
  { ngay: 19, thang:  5, noidung: 'Ngày sinh của Chủ tịch Hồ Chí Minh' },
  { ngay:  1, thang:  6, noidung: 'Ngày Quốc tế Thiếu nhi' },
  { ngay:  5, thang:  6, noidung: 'Ngày Bác Hồ ra đi tìm đường cứu nước' },
  { ngay: 27, thang:  7, noidung: 'Ngày Thương binh Liệt sĩ' },
  { ngay: 19, thang:  8, noidung: 'Ngày Cách mạng tháng Tám thành công' },
  { ngay:  2, thang:  9, noidung: 'Ngày Quốc khánh' },
  { ngay: 13, thang: 10, noidung: 'Ngày Doanh nhân Việt Nam' },
  { ngay: 20, thang: 10, noidung: 'Ngày thành lập Hội Phụ nữ Việt Nam' },
  { ngay: 20, thang: 11, noidung: 'Ngày Nhà giáo Việt Nam' },
  { ngay: 22, thang: 12, noidung: 'Ngày thành lập Quân đội Nhân dân Việt Nam' },
  { ngay: 24, thang: 12, noidung: 'Ngày Lễ Giáng Sinh' },
];
